export const WORD_BANKS: Record<string, string[]> = {
  general: [
    'house',
    'cat',
    'tree',
    'sun',
    'car',
    'flower',
    'fish',
    'cup',
    'star',
    'apple',
    'boat',
    'bird',
    'cake',
    'hat',
    'cloud',
    'heart',
    'moon',
    'ball',
    'book',
    'face',
  ],
  animals: [
    'dog',
    'cat',
    'lion',
    'tiger',
    'elephant',
    'giraffe',
    'zebra',
    'panda',
    'rabbit',
    'monkey',
    'penguin',
    'fox',
    'bear',
    'frog',
    'horse',
    'sheep',
    'duck',
    'whale',
    'owl',
    'chicken',
  ],
  car_brands: [
    'toyota',
    'honda',
    'bmw',
    'audi',
    'mercedes',
    'ford',
    'tesla',
    'porsche',
    'kia',
    'volkswagen',
    'mazda',
    'nissan',
    'hyundai',
    'volvo',
    'lexus',
    'chevrolet',
    'jeep',
    'subaru',
    'bugatti',
    'ferrari',
  ],
  clothes: [
    'shirt',
    't-shirt',
    'hoodie',
    'jacket',
    'coat',
    'dress',
    'skirt',
    'jeans',
    'pants',
    'shorts',
    'sneakers',
    'boots',
    'hat',
    'cap',
    'scarf',
    'gloves',
    'sock',
    'uniform',
    'suit',
    'tie',
  ],
  food: [
    'pizza',
    'burger',
    'noodles',
    'sandwich',
    'sushi',
    'cake',
    'ice cream',
    'salad',
    'ramen',
    'taco',
    'apple pie',
    'hotdog',
    'pasta',
    'bread',
    'dumplings',
    'milk tea',
    'chocolate',
    'steak',
    'donut',
    'curry',
  ],
  characters: [
    'batman',
    'superman',
    'spiderman',
    'iron man',
    'mario',
    'pikachu',
    'doraemon',
    'naruto',
    'goku',
    'luffy',
    'elsa',
    'mickey',
    'donald duck',
    'spongebob',
    'homer simpson'
  ],
  objects: [
    'table',
    'chair',
    'computer',
    'phone',
    'keyboard',
    'mouse',
    'bottle',
    'cup',
    'book',
    'pen',
    'fridge',
    'fan',
    'pencil',
    'backpack',
    'glasses'
  ],
  sports: [
    'football',
    'basketball',
    'tennis',
    'swimming',
    'volleyball',
    'badminton',
    'table tennis',
    'baseball',
    'golf',
    'boxing',
    'running',
    'cycling',
    'skating',
    'skiing',
    'archery'
  ]
};

export const CATEGORY_ALIASES: Record<string, string> = {
  general: 'general',
  default: 'general',
  'thong thuong': 'general',
  'thông thường': 'general',
  'co ban': 'general',
  'cơ bản': 'general',
  animals: 'animals',
  animal: 'animals',
  'dong vat': 'animals',
  'động vật': 'animals',
  'car brands': 'car_brands',
  carbrands: 'car_brands',
  cars: 'car_brands',
  car: 'car_brands',
  xe: 'car_brands',
  'thuong hieu xe': 'car_brands',
  'thương hiệu xe': 'car_brands',
  clothes: 'clothes',
  clothing: 'clothes',
  'quan ao': 'clothes',
  'quần áo': 'clothes',
  food: 'food',
  foods: 'food',
  'do an': 'food',
  'đồ ăn': 'food',
  characters: 'characters',
  character: 'characters',
  'nhan vat': 'characters',
  'nhân vật': 'characters',
  objects: 'objects',
  object: 'objects',
  'vat dung': 'objects',
  'vật dụng': 'objects',
  sports: 'sports',
  sport: 'sports',
  'the thao': 'sports',
  'thể thao': 'sports',
};
